version: '3'

services:
  deliveryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  deliveryservice.services.points:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

