version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'

  neo4j:
    image: neo4j:3.5
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

  deliveryservice.api:
    image: deliveryservice.api
    build:
      context: .
      dockerfile: src/DeliveryService.Api/Dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    ports:
      - '5000:5000'

  deliveryservice.services.points:
    image: deliveryservice.services.points
    build:
      context: .
      dockerfile: src/DeliveryService.Services.Points/Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    links:
      - rabbitmq
      - mongo
    ports:
      - '5050:5050'

